language: go
os: windows
go: 
 - 1.14
script:
 - go build -o zebus.exe
after_success:
 - pwd
 - ls
before_deploy:
 # Set up git user name and tag this commit
 - git config --local user.name "wenchangshou"
 - git config --local user.email "wenchangshou@live.cn"
 - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
 - git tag $TRAVIS_TAG
deploy:
 provider: release
 api_key: "3746b2ea81aee169e5c7044ec60021fd7832173d"
 file: 
  - "zebus.exe"
  - "conf/**/*"
 skip_cleanup: true